### ISSUE TITLE
'routing_key' cannot contain non-alphanumeric characters

### ISSUE THREAD

**Issue by gaia** [blockpane/tenderduty#10]
```
$ td -p blahkeyblah -test -u http://192.168.0.102:26657 -c blahblahvalconsxxxxxxxxxxxxxxxxxxxx
tenderduty   | 2022/02/16 15:52:52 main.go:58: Sending trigger event
2022/02/16 15:52:53 HTTP Status Code: 400, Message: {"status":"invalid event","message":"Event object is invalid","errors":["Length of 'routing_key' is incorrect (should be 32 characters)","'routing_key' cannot contain non-alphanumeric characters."]}

```
The key used is v2. Examples (already removed)
e+23rschqsESqk9Q6_-g
e+kd5BWM-NCknhB3XnYg

I get that this message is generated by a PagerDuty lib, but is it possible this lib is not updated to accept v2 keys?

**Comment by blockpane** [comment]
I haven't seen that error before, but you are 100% correct. I mistakenly used the v1 pagerduty library. I'll take a look at updating.

**Comment by blockpane** [comment]
OK, I see what's going on here. There are two types of API keys available in pagerduty. An events key, and an Oauth API key. They allow access to different things. The event key is available under the services tab, click the "More" button for the service, then "View integrations", "Add integration", and select "Events API V2". 

I've bumped to the latest pager duty lib anyways (I was wrong, it was already using the v2 library.)

**Comment by gaia** [comment]
Yep, problem solved. I am new to pagerduty, I now get that the API key in the traditional sense is the Events API.

![image](https://user-images.githubusercontent.com/87547/154568778-526760b6-d30e-4e04-ab57-b30d41df560d.png)

Should have paid attention that the other API key is under "Developer Tools" and thus isn't the standard use API.

Thanks!
