### ISSUE TITLE
Pass Source Of Alert

### ISSUE THREAD

**Issue by gaia** [blockpane/tenderduty#11]
If I have tenderduty running on multiple servers (for redundancy), it would be useful to be able to pass something similar to `payload.source` in the API, so that'd I know if the service is really down or the RPC relied up by the server is question is N/A. 

As I see it, I'd run two rpcs from each monitoring server, as in
Monitoring Server A: uses its LAN rpc servers
Monitoring Server B: uses its LAN rpc servers

I'd like to know that the validator is indeed down, not just the local RPC server. This is only possible when I get an alert from both Server A and Server B.

**Comment by blockpane** [comment]
So I've actually added a few features in the last couple of days. 

* The first is the ability to add an extra label to the alerts it sends `-label "sent from node1"` or something similar should help. 
* By default, tenderduty does not alert when it has no RPC connections (this was a design choice, my thought was that nodes being down was a different problem.) But, by popular demand I've actually added an option that will allow alerting if it has no RPC node. 

It's possible to pass in a comma separated list of RPC endpoints. If there are multiple it will grab a random one from the list each time it connects.

**Comment by gaia** [comment]
> * The first is the ability to add an extra label to the alerts it sends `-label "sent from node1"` or something similar should help.

Awesome!

> * By default, tenderduty does not alert when it has no RPC connections (this was a design choice, my thought was that nodes being down was a different problem.) But, by popular demand I've actually added an option that will allow alerting if it has no RPC node.

I'm on the same camp with the popular demand. When this is in place it doubles down as an alert for then the RPC is down, which unless is a misconfiguration prob means the whole node is down.

> It's possible to pass in a comma separated list of RPC endpoints. If there are multiple it will grab a random one from the list each time it connects.

Oh, I haven't gotten to try it yet and assumed it would check all of them each time. Only way to reliably know whether the validator is down is to have it checked against multiple sources. Avoiding false positives is my main concern, not so much whether one of the sentries/spare nodes is down or falls behind. Those are cattle/dime a dozen ;)
