### ISSUE TITLE
Websocket Bad Handshake Error

### ISSUE THREAD

**Issue by Relyte** [blockpane/tenderduty#14]
**OS**: Ubuntu 20.04
**Go Version**: go1.18.1 linux/amd64

**Issue**:
Tenderduty cannot connect to remote RPC server and fails with a "websocket: bad handshake" error.

**Command**: 
./tenderduty -c darcvalcons12345... -p <pagerduty_api_key> -u "https://node1.konstellation.tech:26657"

**Expected output:** 
Tenderduty connects to the RPC server and starts monitoring the address

**Actual Outcome**:
Tenderduty fails to run with the following error:
```
tenderduty   | 2022/04/26 15:53:27 main.go:88: checking that at least 1 of 1 endpoints are available
tenderduty   | 2022/04/26 15:53:27 main.go:183: Warning: could not connect to https://node1.konstellation.tech:26657 websocket: bad handshake
tenderduty   | 2022/04/26 15:53:27 main.go:91: FATAL:no RPC endpoints are available
```

**Workarounds**:
None found so far

**Notes**:
This is also occurring when run in a Docker container.
The RPC server appears to be functioning normally outside of Tendermint.

**Comment by blockpane** [comment]
This is an issue with the Tendermint RPC client, and it's not likely to be fixed anytime soon without an upstream patch.  I've spent hours trying to track down what's going on in the code. The wss support in the client is incomplete and somehow it messes up the Dialer it hands off to Gorilla. There are probably other issues beyond that. I've had a difficult time trying to debug it. Maybe the correct approach would be to skip using the TM client entirely and just use Gorilla. I'll have to think about how difficult that would be, probably not a horribly big refactor.

**Comment by blockpane** [comment]
Good news on this, for tenderduty v2 I've tenderduty will just use gorilla directly, and not use the tendermint client for websocket connections. This is working on the pre-alpha version, but going to leave the ticket open until there is a beta release.

**Comment by neo676** [comment]
Fantastic tool! Already running from Releasev2 branch.

The tool isn't connecting to the next RPC endpoint when multiple are given, and basically is stuck with the one failing one. 

In my case, I had used 
```
      - url: https://cosmos-rpc.polkachu.com:443
        alert_if_down: no
      - url: https://rpc.cosmos.network:443
        alert_if_down: no
```

But it doesn't even get to the second rpc server, the below error keeps looping and I see 0/2 connected in dashboard,
```
6:20:41 PM - could not dial ws client to wss://cosmos-rpc.polkachu.com:443/websocket: websocket: bad handshake
6:20:41 PM - ⚙️ found cosmosvaloper1sjllsnramtg3ewxqwwrwjxfgc4n4ef9u2lcnj0 (🐠stake.fish) in validator set
...
```

But when removing the polkachu rpc, it connects to the rpc.cosmos.network and happily.

Thanks for the great work!

**Comment by blockpane** [comment]
Tenderduty v2 now uses the gorilla websocket client instead of tendermint's. TLS now works
