### ISSUE TITLE
Cleanup alarm state - stalled chain

### ISSUE THREAD

**Issue by m8nky** [blockpane/tenderduty#27]
After the chain has been stalled (not producing blocks for more than 10 minutes), and the chain has been restored, the notification is still marked active.

Observed with Terra2 testnet upgrade today. Chain was waiting for 2/3 quorum for a couple of hours, alarm was raised as expected after 10 min. But does not invalidate the state, even after restart of Tenderduty.

`10:50:29 PM - 📂 restored %s alarm state - dashboard stalled: have not seen a new block on pisco-1 in 10 minutes`

Expected: Automatic alarm state cleanup, IF the chain is producing again AND the validator participates in voting/proposals as expected.

**Comment by gaia** [comment]
Still seeing this issue on v2.2.0
