### ISSUE TITLE
panic: pubkey is incorrect size

### ISSUE THREAD

**Issue by iiimoon** [blockpane/tenderduty#34]
receiving error for Bandprotocol setup.  

Error stack 

panic: pubkey is incorrect size
github.com/cosmos/cosmos-sdk/crypto/keys/ed25519.(*PubKey).Address(0xc001145bd0?)
/var/lib/tenderduty/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.5/crypto/keys/ed25519/ed25519.go:161 +0x9a
github.com/blockpane/tenderduty/v2/td2.getVal({0x14052e0, 0xc00104e0c0}, 0xc0004f85a0, {0xc000f84940, 0x32})
 /var/lib/tenderduty/tenderduty/td2/validator.go:159 +0x19d
github.com/blockpane/tenderduty/v2/td2.(*ChainConfig).GetValInfo(0xc000f8e900, 0x1)
/var/lib/tenderduty/tenderduty/td2/validator.go:43 +0x105
github.com/blockpane/tenderduty/v2/td2.Run.func4(0xc000f8e900, {0xc00027eff4, 0x4})
/var/lib/tenderduty/tenderduty/td2/run.go:100 +0x1dc
created by github.com/blockpane/tenderduty/v2/td2.Run
/var/lib/tenderduty/tenderduty/td2/run.go:81 +0x46e

I recreated with multiple validator  address from Band , here is one for example. - bandvaloper1wwl9d8gvpktdjhdpzxe9yupunpkthzayysf2hn

https://www.mintscan.io/band/validators/bandvaloper1wwl9d8gvpktdjhdpzxe9yupunpkthzayysf2hn

**Comment by social244305-Architect** [comment]
Any update on this issue?

**Comment by blockpane** [comment]
Fixed in v2.2.0
