### ISSUE TITLE
Feature: Support minimum-signed threshold

### ISSUE THREAD

**Issue by BOSEES** [blockpane/tenderduty#79]
# Purpose
The fundamental of tenderduty is to check the validator's uptime, but there is an inconvenience in intuitively understanding the risk level. For example, we run a lot of validators and use a different minSignedPerWindow for each protocol. It's very annoying to manually query the nodes, so we add a feature to visually see the threshold.

<img width="385" alt="threshold" src="https://github.com/blockpane/tenderduty/assets/65009591/c26b58d9-209c-428c-acc2-8b8d1eaae043">

# Impact
Intuitively understand the risk level of your validators.

**Comment by dylanschultzie** [comment]
Merged. Thanks for your contribution!
